import type { PaginatedResult } from "@/lib/pagination";

/**
 * File Storage (Phase 6), Module 6.2 — ONE reusable storage
 * architecture, not a per-module upload implementation. Every business
 * module this app has today (CRM/Leads/Conversations/WhatsApp/Email/
 * Campaigns) and every one it doesn't yet (Student Portal, LMS, more
 * SaaS tenants) is meant to call `fileStorageService`, never a
 * concrete provider or `fs`/vendor SDK directly.
 */

export type StorageProviderId = "local" | "aws_s3" | "cloudinary";

export type FileCategory =
  | "IMAGE"
  | "VIDEO"
  | "AUDIO"
  | "DOCUMENT"
  | "CSV"
  | "AVATAR"
  | "ORGANIZATION_ASSET"
  | "WHATSAPP_MEDIA"
  | "EMAIL_ATTACHMENT"
  | "CRM_ATTACHMENT"
  | "EXPORT"
  | "OTHER";

export type FileVisibility = "public" | "private";

/**
 * The generic provider abstraction — every capability the mission
 * names, and nothing vendor-specific leaks past this interface.
 * `upload()` always receives bytes already in memory (this app never
 * handles files large enough to need streaming/multipart uploads);
 * `storageKey` is always generated by the caller (fileStorageService),
 * never derived from user input — see validation.ts's own doc comment
 * on why that's the real path-traversal defense.
 */
export interface StorageUploadInput {
  storageKey: string;
  buffer: Buffer;
  mimeType: string;
  visibility: FileVisibility;
}

export interface StorageUploadResult {
  storageKey: string;
  /** Set only when the provider can serve this key without any
   *  further authentication (a real public S3/Cloudinary URL, or the
   *  provider's own CDN). Undefined for anything private, and always
   *  undefined for the local provider (dev has no real public host —
   *  see LocalStorageProvider's own doc comment). */
  publicUrl?: string;
}

/** RC-2 — "safe downloads": every provider's signed URL forces a real
 *  file download (`Content-Disposition: attachment`) rather than
 *  letting a browser render the response inline at whatever origin
 *  serves it — the actual control that stops an uploaded HTML/SVG
 *  file from executing as a page rather than being downloaded as a
 *  file, Content-Type allowlisting/magic-byte checks alone don't
 *  prevent this. `filename` is the FileAsset's own `originalFilename`;
 *  omitted callers get the provider's own default disposition. */
export interface StorageDownloadOptions {
  mimeType?: string;
  filename?: string;
}

export interface StorageProvider {
  readonly id: StorageProviderId;
  upload(input: StorageUploadInput): Promise<StorageUploadResult>;
  delete(storageKey: string): Promise<void>;
  exists(storageKey: string): Promise<boolean>;
  /** Null when this key has no directly-fetchable public URL (private
   *  visibility, or a provider with no CDN concept). */
  getPublicUrl(storageKey: string): string | null;
  /** A time-limited URL for private access — every provider must
   *  support this even where it means "reads back through this app's
   *  own authenticated proxy" rather than a real vendor-signed URL
   *  (see LocalStorageProvider/CloudinaryProvider's own doc comments). */
  getSignedUrl(storageKey: string, expiresInSeconds: number, downloadOptions?: StorageDownloadOptions): Promise<string>;
}

/**
 * The centralized File/Asset metadata row — one per uploaded object,
 * regardless of which provider or business module created it.
 * `relatedEntityType` is a plain string, not a closed union: unlike
 * Activity's own polymorphic entityType (closed to Lead/Opportunity/
 * Conversation, since only those three modules produce activities),
 * File is explicitly meant to be reusable by modules that don't exist
 * yet — a closed union here would need editing on every future
 * module, exactly the coupling this module exists to avoid.
 */
export interface FileAsset {
  id: string;
  provider: StorageProviderId;
  storageKey: string;
  originalFilename: string;
  /** Sanitized, human-readable name shown in the UI — distinct from
   *  `storageKey` (the opaque, collision-proof path the provider
   *  actually stores under). */
  storedFilename: string;
  mimeType: string;
  extension: string;
  sizeBytes: number;
  category: FileCategory;
  /** sha256 of the uploaded bytes — integrity/dedup signal, not
   *  verified against anything external. */
  checksum: string;
  visibility: FileVisibility;
  /** Denormalized from the provider at upload time so reads never
   *  need a provider round-trip just to render a public `<img>` tag —
   *  same "avoid per-row aggregation on a read path" precedent
   *  Conversation.lastMessagePreview already established. */
  publicUrl?: string;
  uploadedBy?: string;
  relatedEntityType?: string;
  relatedEntityId?: string;
  /** Business OS Phase 0 — tenant scaffolding, unset until multi-tenant
   *  activation (Phase 8), the same convention every other collection
   *  in this app already follows (see Module 6.1's own IntegrationConnection
   *  for the identical reasoning). */
  organizationId?: string;
  createdAt: string;
  updatedAt: string;
  /** Soft-delete only — the provider's own bytes are removed
   *  immediately on delete, but the metadata row persists with this
   *  timestamp set, so "who deleted what, when" stays answerable
   *  without needing a separate audit-only trail for it. */
  deletedAt?: string;
}

export interface CreateFileAssetInput {
  provider: StorageProviderId;
  storageKey: string;
  originalFilename: string;
  storedFilename: string;
  mimeType: string;
  extension: string;
  sizeBytes: number;
  category: FileCategory;
  checksum: string;
  visibility: FileVisibility;
  publicUrl?: string;
  uploadedBy?: string;
  relatedEntityType?: string;
  relatedEntityId?: string;
  organizationId?: string;
}

export interface FileAssetListFilters {
  relatedEntityType?: string;
  relatedEntityId?: string;
  category?: FileCategory;
  /** Defaults to false (soft-deleted files excluded) at the service
   *  layer, same "not defaulted in the repository" precedent Lead's
   *  own `archived` filter already established. */
  includeDeleted?: boolean;
}

export interface FileAssetRepository {
  findById(id: string): Promise<FileAsset | null>;
  create(input: CreateFileAssetInput): Promise<FileAsset>;
  list(filters: FileAssetListFilters, page: number, limit: number): Promise<PaginatedResult<FileAsset>>;
  softDelete(id: string): Promise<FileAsset>;
}
