import { promises as fs } from "fs";
import path from "path";
import { LOCAL_STORAGE_CONFIG } from "@/config/storage";
import { createLocalSignedUrl } from "../signedUrl";
import type { StorageDownloadOptions, StorageProvider, StorageUploadInput, StorageUploadResult } from "../types";

/**
 * Default/dev provider — real, working, not a stub, the same role
 * Email's "console" and WhatsApp's own console provider play: safe to
 * use from day one with zero external account. Writes real bytes to a
 * gitignored local directory (`.storage-uploads/` by default), never
 * inside `public/` — Next.js never serves these as static assets, the
 * only way to read one back is through this app's own authenticated
 * download route or a signed URL (see signedUrl.ts). Not intended for
 * a real multi-instance/serverless production deployment (local disk
 * isn't shared or durable there) — that's exactly why AWS S3/Cloudinary
 * exist as the real options.
 */
function resolvePath(storageKey: string): string {
  // storageKey is always generated by fileStorageService, never derived
  // from user input (see validation.ts) — this join is safe by
  // construction, but the extra `..`-segment check costs nothing and
  // means this provider is safe even if a future caller ever passes
  // something less trusted.
  const normalized = path.normalize(storageKey);
  if (normalized.split(path.sep).includes("..")) {
    throw new Error(`Refusing to resolve a storageKey containing "..": ${storageKey}`);
  }
  return path.join(process.cwd(), LOCAL_STORAGE_CONFIG.directory, normalized);
}

export const localStorageProvider: StorageProvider = {
  id: "local",

  async upload(input: StorageUploadInput): Promise<StorageUploadResult> {
    const filePath = resolvePath(input.storageKey);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, input.buffer);
    // Never a public URL — see this file's own top comment.
    return { storageKey: input.storageKey };
  },

  async delete(storageKey: string): Promise<void> {
    try {
      await fs.unlink(resolvePath(storageKey));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  },

  async exists(storageKey: string): Promise<boolean> {
    try {
      await fs.access(resolvePath(storageKey));
      return true;
    } catch {
      return false;
    }
  },

  getPublicUrl(): string | null {
    return null;
  },

  async getSignedUrl(storageKey: string, expiresInSeconds: number, downloadOptions?: StorageDownloadOptions): Promise<string> {
    return createLocalSignedUrl(storageKey, expiresInSeconds, downloadOptions);
  },

  async listAllKeys(): Promise<string[]> {
    const root = path.join(process.cwd(), LOCAL_STORAGE_CONFIG.directory);
    const keys: string[] = [];
    async function walk(dir: string): Promise<void> {
      let entries;
      try {
        entries = await fs.readdir(dir, { withFileTypes: true });
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
        throw error;
      }
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          await walk(fullPath);
        } else {
          // storageKey is always POSIX-style ("category/uuid.ext" — see
          // validation.ts's generateStorageKey) regardless of the host
          // OS's own path separator.
          keys.push(path.relative(root, fullPath).split(path.sep).join("/"));
        }
      }
    }
    await walk(root);
    return keys;
  },
};

/** Exported for the local-signed-URL delivery route only — reads the
 *  real bytes + a best-effort content type guess is NOT this
 *  function's job (the FileAsset row already knows the real mimeType;
 *  the route reads that separately). */
export async function readLocalFile(storageKey: string): Promise<Buffer> {
  return fs.readFile(resolvePath(storageKey));
}
