import { NextResponse } from "next/server";
import { withApiRoute } from "@/lib/api";
import openapiSpec from "@/docs/api/openapi.json";

/**
 * GET /api/docs/openapi.json
 *
 * RC-8 — Documentation, API Documentation & Operational Knowledge
 * Base. Serves the real, mechanically-generated OpenAPI 3.1 spec
 * (docs/api/openapi.json, regenerated by
 * scripts/docs/generateOpenApiSpec.ts from the actual withApiRoute()
 * registrations across every app/api/**\/route.ts file — never
 * hand-maintained, never invented). `requiredRole: "admin"` — this
 * spec enumerates every internal and Platform Console route this
 * deployment has (paths, required roles, rate limits), which is
 * developer-internal information, not something to expose
 * unauthenticated (mission's own §10/§45 instruction). Any signed-in
 * tenant Admin may read it; it does not require Platform Super Admin,
 * since it describes this deployment's own API surface, not another
 * tenant's data.
 */
async function handleGetOpenApiSpec(): Promise<NextResponse> {
  return NextResponse.json(openapiSpec);
}

export const GET = withApiRoute("docs.openapi_spec", handleGetOpenApiSpec, {
  requiredRole: "admin",
  rateLimit: { limit: 30, windowMs: 60_000 },
});
